#当提交被推送到您的默认分支时，此工作流将构建node.js应用程序并将其推送到Azure Web App。
#
#此工作流假设您已经创建了目标Azure应用服务web应用.
#有关说明,请参见https://docs。微软。com/en-us/azure/app-service/quick start-nodejs？tabs = linux & pivots =开发-环境-cli
#
#要配置此工作流:
#
# 1.为您的Azure Web应用下载发布配置文件。您可以从蔚蓝的门户中您的网应用的概述页面下载该文件。
#了解更多信息:https://docs。微软。com/en-us/azure/app-service/deploy-github-actions？tabs = applevel #生成-部署-凭证
#
# 2.在名为AZURE_WEBAPP_PUBLISH_PROFILE的存储库中创建一个秘密,将发布配置文件的内容粘贴为秘密的值。
#有关获取发布配置文件的说明,请参见:https://docs。微软。com/azure/app-service/deploy-github-actions # configure-the-github-secret
#
# 3.更改AZURE_WEBAPP_NAME的值。或者,更改下面的AZURE_WEBAPP_PACKAGE_PATH和节点版本环境变量。
#
#有关开源代码库对蔚蓝的的操作的更多信息:https://github . com/Azure/Actions
#有关Azure网络应用部署操作的更多信息:https://github . com/Azure/web apps-deploy
#获取更多部署到蔚蓝的的开源代码库动作工作流的示例:https://github . com/Azure/actions-workflow-samples

在:
推:
分支: [分支:[ "主要" ]"主要" ]
工作流_调度:

包封/包围（动词envelop的简写）:
AZURE_WEBAPP_NAME: AZURE _ web app _ NAME:your-app-NAME #将此设置为您的应用程序的名称#将此设置为应用程序的名称
AZURE_WEBAPP_PACKAGE_PATH: '.'AZURE_WEBAPP_PACKAGE_PATH:“”#将此项设置为web应用程序项目的路径，默认为存储库根目录# set this to the path to your web app project, defaults to the repository root
节点版本: 14.x 'NODE_VERSION: 14.x ' #将此设置为要使用的节点版本#将其设置为要使用的节点版本

许可:
内容: 内容:阅读

工作:
建设:
连续运行: 运行:Ubuntu-最新版
步伐:
    - 使用: -用途:actions/checkout@v3

    - 名字: -名称:设置Node.js
使用: 用法:actions/setup-node@v3
随着:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
